name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add tools to PATH
        shell: powershell
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Sonar Begin
        shell: powershell
        run: |
          dotnet-sonarscanner begin `
            /k:"steven-patterson17_Vr_Training_Application" `
            /o:"steven-patterson17" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.sources="Assets"

      - name: Sonar End
        shell: powershell
        run: |
          dotnet-sonarscanner end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
